<?php

namespace Acme\HelloBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * FacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacesRepository extends EntityRepository{
    
    public function findFacesOver(){
        
        $sql = "SELECT full_name,"
                . " ((YEAR(CURRENT_DATE) - YEAR(birth_date)) - (DATE_FORMAT(CURRENT_DATE, '%m%d')"
                . " < DATE_FORMAT(birth_date, '%m%d')))"
                . " AS age FROM faces"
                . "  WHERE (YEAR(CURRENT_DATE) - YEAR(birth_date)) - (DATE_FORMAT(CURRENT_DATE, '%m%d')"
                . " < DATE_FORMAT(birth_date, '%m%d')) > 20";

        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();
        
        return $stmt->fetchAll();
    }
}