<?php

namespace Acme\HelloBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KidsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KidsRepository extends EntityRepository{
    
    public function findKidsOver(){
        
        $sql = "SELECT faces.full_name, count(kids.f_id)"
                . " AS count, (YEAR(CURRENT_DATE)-YEAR(kids.birth_date))-(RIGHT(CURRENT_DATE, 5)"
                . " < RIGHT(kids.birth_date, 5))"
                . " AS age"
                . " FROM faces, kids"
                . " WHERE (YEAR(CURRENT_DATE)-YEAR(kids.birth_date))-(RIGHT(CURRENT_DATE, 5)"
                . " < RIGHT(kids.birth_date, 5)) < 7"
                . " AND kids.f_id = faces.f_id"
                . " GROUP BY faces.full_name";
        
        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();
        
        return $stmt->fetchAll();
    }
}
